---
apiVersion: v1
kind: Service
metadata:
  name: common-csm
  labels:
    app: common-csm
spec:
  ports:
    - port: 8085
      name: common-csm
      targetPort: 8080
  selector:
    app: common-csm
    tier: frontend
  type: LoadBalancer
